# fly.toml file generated for deploy-pokedex on 2022-10-20T19:19:22-03:00

app = "deploy-pokedex"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
  app = "node app.js"

# NOTE: heroku/buildpacks is EXTREMELY slow to transfer operations, specially non-size-optimized images of 1GB+.
# NOTE: Took ~30min just to end up in a failed build. Using size-optimized Dockerfile instead buildpacks on deploy/ folder.
# [build]
  # builder = "heroku/buildpacks:20"

[deploy]
  release_command = "npm run build"

[env]
  PORT = "5000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"