name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "🚩[ EXECUTE ]: npm install"
        run: npm install
      - name: "🚩[ EXECUTE ]: lint and fix source code"
        run: npm run eslint:fix
      - name: "🚩[ EXECUTE ]: test source code"
        run: npm test
      - name: "🚩[ EXECUTE ]: prepare cypress dependencies"
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: e2e tests
        uses: cypress-io/github-action@v2
        # env:
        #   DEBUG: "@cypress/github-action"
        with:
          command: npm run test:e2e
          start: |
            npm run build
            npm run start-prod
          wait-on: http://localhost:5000
      - name: "Deploy to Fly.io"
        if: ${{ github.event_name == 'push' }}
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          run: cd deploy && flyctl deploy
      - name: Notify on deploy success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
            severity: info
            details: "[ Success ]: deploy complete and uploaded"
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      - name: Notify on deploy fail
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
            severity: error
            details: "[ Error ]: deploy aborted"
            args: "Commit: ${{ github.event.head_commit }} | ${{ github.event_name }} event triggered by ${{ github.event.actor }}"
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://deploy-pokedex.fly.dev|http://deploy-pokedex.fly.dev
          follow-redirect: false
          max-attempts: 3
          retry-delay: 86400s
          retry-all: false

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, '#skip')"
    steps:
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          POKEDEX_GITHUB_TOKEN: ${{ secrets.POKEDEX_GITHUB_TOKEN }}
