name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "🚩[ EXECUTE ]: npm install"
        run: npm install
      - name: "🚩[ EXECUTE ]: lint and fix source code"
        run: npm run eslint:fix
      - name: "🚩[ EXECUTE ]: test source code"
        run: npm test
      - name: "🚩[ EXECUTE ]: prepare cypress dependencies"
        run: |
          apt update
          apt install --no-install-recommends -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: e2e tests
        uses: cypress-io/github-action@v2
        # env:
        #   DEBUG: "@cypress/github-action"
        with:
          command: npm run test:e2e
          start: |
            npm run build
            npm run start-prod
          wait-on: http://localhost:5000
      - name: "Deploy to Fly.io"
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          run: cd deploy && flyctl deploy
